name: ParisLille3D
cache_dir: ./logs/cache
class_weights:
- 5181602
- 5012952
- 6830086
- 1311528
- 10476365
- 946982
- 334860
- 269353
- 269353
dataset_path: ../dataset/Paris_Lille_3D/
ignored_label_inds:
- 0
num_points: 65536
prepro_grid_size: 0.06
test_dir: ../dataset/Paris_Lille_3D/test_10_classes/
test_result_folder: ./test
train_dir: ../dataset/Paris_Lille_3D/training_10_classes/
val_files:
- Lille2.ply