name: Semantic3D
cache_dir: .logs/cache/
class_weights:
- 5181602
- 5012952
- 6830086
- 1311528
- 10476365
- 946982
- 334860
- 269353
dataset_path: ./datasets/Semantic3D/
ignored_label_inds:
- 0
num_points: 65536
prepro_grid_size: 0.06
test_result_folder: ./test
use_cache: true
val_split: 1