name: Toronto3D
dataset_path: # path/to/your/dataset
cache_dir: ./logs/cache
class_weights: [5181602, 5012952, 6830086, 1311528, 10476365, 946982, 334860, 269353]
ignored_label_inds:
- 0
num_points: 65536
prepro_grid_size: 0.06
test_files:
- L002.ply
test_result_folder: ./test
train_files:
- L001.ply
- L003.ply
- L004.ply
val_files:
- L002.ply