dataset:
  name: ParisLille3D
  dataset_path: # path/to/your/dataset
  cache_dir: ./logs/cache
  class_weights: [65075320, 33014819, 656096, 61715, 296523, 4052947, 172132,4212295, 10599237]
  ignored_label_inds:
  - 0
  num_points: 65536
  prepro_grid_size: 0.06
  test_result_folder: ./test
  val_files:
  - Lille2.ply
  use_cache: False
model:
  name: RandLANet
  batcher: DefaultBatcher
  ckpt_path: # path/to/your/checkpoint
  dim_feature: 8
  dim_input: 3
  dim_output:
  - 16
  - 64
  - 128
  - 256
  - 512
  grid_size: 0.06
  ignored_label_inds:
  - 0
  k_n: 16
  num_classes: 9
  num_layers: 5
  num_points: 65536
  num_sub_points:
  - 16384
  - 4096
  - 1024
  - 256
  - 128
  sub_grid_size: 0.06
  sub_sampling_ratio:
  - 4
  - 4
  - 4
  - 4
  - 2
pipeline:
  name: SemanticSegmentation
  adam_lr: 0.01
  batch_size: 1
  learning_rate: 0.01
  main_log_dir: ./logs
  max_epoch: 100
  save_ckpt_freq: 20
  scheduler_gamma: 0.95
  test_batch_size: 1
  train_sum_dir: train_log
  val_batch_size: 1
