dataset:
  name: Toronto3D
  cache_dir: ./logs/cache
  dataset_path: # path/to/your/dataset
  class_weights: [5181602, 5012952, 6830086, 1311528, 10476365, 946982, 334860, 269353]
  ignored_label_inds:
  - 0
  num_points: 65536
  prepro_grid_size: 0.06
  test_files:
  - L002.ply
  test_result_folder: ./test
  train_files:
  - L001.ply
  - L003.ply
  - L004.ply
  use_cache: true
  val_files:
  - L001.ply
model:
  name: RandLANet
  batcher: DefaultBatcher
  ckpt_path: #./logs/RandLANet_torch/checkpoint/ckpt_480.pth # path/to/your/checkpoint
  dim_feature: 8
  dim_input: 3
  dim_output:
  - 16
  - 64
  - 128
  - 256
  - 512
  grid_size: 0.06
  ignored_label_inds:
  - 0
  k_n: 16
  num_classes: 8
  num_layers: 5
  num_points: 65536
  num_sub_points:
  - 16384
  - 4096
  - 1024
  - 256
  - 128
  sub_grid_size: 0.06
  sub_sampling_ratio:
  - 4
  - 4
  - 4
  - 4
  - 2
pipeline:
  name: SemanticSegmentation
  adam_lr: 0.01
  batch_size: 1
  learning_rate: 0.01
  main_log_dir: ./logs
  max_epoch: 10000
  save_ckpt_freq: 20
  scheduler_gamma: 0.99
  test_batch_size: 1
  train_sum_dir: train_log
  val_batch_size: 1
